development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: dbcoverflow_development
  pool: 5

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: dbcoverflow_test
  pool: 5

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: dbcoverflow_production
  pool: 5